name: H1Androidapp-Scope
on: 
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # run once an hour
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
        
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git pull origin main --rebase
    
    - name: Create local changes
      run: |
        chmod +x run.sh
        ./run.sh
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main

